name: 'build'

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        idf_ver: ["v4.1", "v4.2", "v4.3"]
        idf_target: ["esp32"]
        include:
          - idf_ver: "v4.2"
            idf_target: esp32s2
          - idf_ver: "v4.3"
            idf_target: esp32c3
    runs-on: ubuntu-20.04
    container: espressif/idf:release-${{ matrix.idf_ver }}
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: Build ESP examples
        env:
          IDF_TARGET: ${{ matrix.idf_target }}
        shell: bash
        run: |
          cd examples/wemos_lolin_oled/hello_world
          . ${IDF_PATH}/export.sh
          idf.py build
